### ISSUE TITLE
Extending duration when less records than limit returned

### ISSUE THREAD

**Issue by matthewmoss** [biola/punching_bag#15]
Hello, I am try to create a trending system for search. A punch is made every time a search is made. In order to only show recently trending searches, I do as shown bellow to fetch the records. This works great except when less objects are returned than the limit I pass in. Although objects that have been searched for in the last day should appear first, if not enough to reach the limit have, it would be great if the time limit was extended until the limit is met, therefore always returning the same amount of results.

Object.most_hit(1.week.ago, 3)

**Comment by adamcrown** [comment]
Sorry it's taken me so long to get back to you about this. I could see that this could be a nice feature. Probably best implemented as an option for the method.

I'll see if I can get this working easily without impacting performance much.

**Comment by adamcrown** [comment]
So I started looking into this and my concern is that there's a couple different ways this could be done and depending on how you'd assume it would work you could wind up with misleading results.

__Method 1__ would be the most accurate but the most problematic and the poorest performing. Basically, it would involve incrementing the `since` argument until the limit is reached.

__Method 2__ the second method would preform better but wouldn't be very accurate because you'd just ignore the `since` argument and grab the top records that way.

At this point I think I prefer to just let developers choose which they want in their own code. Both methods should be fairly simple to implement.

```ruby
limit = 3

top = Object.most_hit(1.week.ago, limit)
top = Object.most_hit(nil, limit) if top < limit
```

```ruby
since = 1.week
limit = 3

top = []
new_since = since.dup
while top.length < limit && new_since < since * 10
  top = Object.most_hit(Time.now - since, limit)
  new_since = new_since + since
end
```

*This code is untested and may not work but you get the idea*
